"""create review table

Revision ID: 6180669c137b
Revises: 4b5b62a642a0
Create Date: 2025-12-13 18:07:32.707027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6180669c137b'
down_revision = '4b5b62a642a0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('key_points', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
